### ISSUE TITLE
Feature request: Use TypeScript breakpoints for a debug session of a JavaScript file with source maps

### ISSUE THREAD

**Issue by AndrewFerr** [eclipse-wildwebdeveloper/wildwebdeveloper#972]
If a JavaScript file has a source map that refers to a TypeScript file, it would be nice if debug sessions for the JavaScript file (launched via Debug As > Node program) would pause on breakpoints set on the mapped TypeScript file.  Currently, doing so has WWD ignore breakpoints on the TypeScript file.

This feature would be analogous to running `node --inspect-brk` on a JavaScript file & attaching to it.

This would also alleviate WWD's reliance on a `tsconfig.json` file to debug a TypeScript file: instead of needing a `tsconfig.json` to map a TypeScript file to its corresponding JavaScript (and to figure out which JavaScript file to launch with Node), WWD could use source maps to map a JavaScript file to its corresponding TypeScript file (which has the added bonus of knowing right away which file to launch with Node, as it's a JavaScript file in the first place).

**Comment by mickaelistria** [comment]
I would consider it as a bug instead of a feature request.
Can you please share a minimal project and minimal steps to reproduce this issue?

**Comment by AndrewFerr** [comment]
Minimal project structure is a `tsconfig.json` of:
```
{
  "compilerOptions": {
    "sourceMap": true,
    "outDir": "lib",
    "rootDir": "src"
  }
}
```
and a single `*.ts` file in `./src`.  Build it with `tsc -b` (via `npx` or `yarn` as needed); put a breakpoint on the corresponding JS file in `./lib/*.js`; and debug it with Debug As > Node program.

**Comment by vrubezhny** [comment]
I believe this issue is fixed wiith https://github.com/eclipse/wildwebdeveloper/pull/1064

Please,update WWD from the latest snapshots. Feel free to reopen if this is still a relevant issue. Thanks

**Comment by AndrewFerr** [comment]
No, the original issue is still present, even with the latest updates applied (including the fix for #973).

But I realize now that my [reproduction steps](https://github.com/eclipse/wildwebdeveloper/issues/972#issuecomment-1322096526) were incorrect; I've updated them appropriately.

**Comment by AndrewFerr** [comment]
Also, it appears that I don't have the ability to reopen issues in this repo, so please reopen this when you have a chance.

**Comment by mickaelistria** [comment]
I think this is fixed with https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/pull/1174
